### ISSUE TITLE
Messages get left behind, sometimes not deleted because of network latency.

### ISSUE THREAD

**Issue by ventris64x** [hellbound1337/clear-messages#2]
Possible Fixes:
- Creating a message queue and slowing it down if one message was missed, waiting the time period then retrying deletion on that message and resuming the queue

`body.retry_after` can be used to define how long before the queue resumes.

**Comment by LilSizzurp** [comment]
It should already do that? [Delete function](https://github.com/hellbound1337/clear-messages/blob/master/index.js#L105)
